// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1s7d1bJTUZzzzCucgHquaVd_15CPQ3EU',
    appId: '1:230769555731:web:a034e1679c3e8920c202e6',
    messagingSenderId: '230769555731',
    projectId: 'loginapp-77a47',
    authDomain: 'loginapp-77a47.firebaseapp.com',
    storageBucket: 'loginapp-77a47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9G8r2z0uqOvTnFSnNRQj0VhKCDb-Qxno',
    appId: '1:230769555731:android:5153a16e654edb45c202e6',
    messagingSenderId: '230769555731',
    projectId: 'loginapp-77a47',
    storageBucket: 'loginapp-77a47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnC4RunpFF8_rkHxA_xlRZFnUgcLHH-g',
    appId: '1:230769555731:ios:ab1cb2242650b828c202e6',
    messagingSenderId: '230769555731',
    projectId: 'loginapp-77a47',
    storageBucket: 'loginapp-77a47.appspot.com',
    iosClientId: '230769555731-m959fm9jnhkde8b8kii57kr4jermucna.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnC4RunpFF8_rkHxA_xlRZFnUgcLHH-g',
    appId: '1:230769555731:ios:ab1cb2242650b828c202e6',
    messagingSenderId: '230769555731',
    projectId: 'loginapp-77a47',
    storageBucket: 'loginapp-77a47.appspot.com',
    iosClientId: '230769555731-m959fm9jnhkde8b8kii57kr4jermucna.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
